### ISSUE TITLE
Get token method: security leak?

### ISSUE THREAD

**Issue by chasseurmic** [subhransu/railsauth#1]
In ApiController why is the _get_token_ method so _open_? I mean, just by knowing the email address anyone could sniff the auth_token and behave as the victim. Am I wrong or missing something?

Thanks.

**Comment by subhransu** [comment]
Hi,

get_token is also secured by Basic Authentication. So in order to get a new token for an user you still need to pass the basicauth username and password in your request header. Without those it would fail.

Let me know if you still notice any issues!
- subh
